### ISSUE TITLE
Figure out procedure for archiving accepted PLEPs on Zenodo

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/PlasmaPy-PLEPs#15]
When we finish PLEPs, it will be really helpful to archive them on Zenodo for long-term storage and to make them citeable.  We should figure out the procedure for how to do that, and put that information in PLEP 1 which is being written in #11.

Zenodo has a good way of archiving evolving documents.  If we update a PLEP, then we can upload the revised version to Zenodo under a different DOI.  As we are doing that, we will be able to say that the revised version is a new version of the older version.  If we do that, then we will be able to handle PLEPs as living documents that get amended.

**Comment by lemmatum** [comment]
I was just listening to a Talk Python To Me episode on the Journal of Open Source Software, and they mentioned Zenodo! One thing to be careful about (which was discussed in the podcast) is that Zenodo currently doesn't save the git commit history, though I don't think this will be a problem with we keep PlasmaPy-PLEPs around on Github :smile:
